ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeapp.urls')),
    path('cart/', include('cartapp.urls')),
    path('adminsection/', include('adminapp.urls')),
   
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'homeapp.views.error_page'

ecom/homeapp/models.py
from django.db import models
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.template.defaultfilters import slugify





STATE_CHOICES = (
    ('Kerala','Kerala'),
    ('Tamilnadu','Tamilnadu'),
    ('Karnataka','Karnataka'),
    ('AndraPradesh','AndraPradesh')
)
DIST_CHOICES = {
    ('Kannur','Kannur'),
    ('Kozhikkode','Kozhikkode'),
    ('Ernakulam','Ernakulam'),
    ('Thiruvananthapuram','Thiruvananthapuram'),
    ('Banglore','Banglore'),
    ('Hubli','Hubli'),
    ('Hydrabad','Hydrabad'),
    ('Coimbator','Coimbator'),
    ('Madurai','Madurai'),
}

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    mobile_regex = RegexValidator(regex=r'^\d+$', message="Mobile number should only contain digits")
    mobile = models.CharField(validators=[mobile_regex], max_length=10, null=True)
    address = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='user', null=True, blank=True)
    district = models.CharField(choices=DIST_CHOICES,max_length=20, null=True, blank=True)
    state = models.CharField(choices=STATE_CHOICES,max_length=20, null=True)
    pincode_regex = RegexValidator(regex=r'^\d+$', message="Pincode should only contain digits")
    pincode = models.PositiveIntegerField(null=True, blank=True)
    otp = models.CharField(max_length=6, null=True, blank=True)
    is_verified = models.BooleanField(default=False)
    is_blocked = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username






class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name



class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    price = models.PositiveBigIntegerField()
    stock = models.PositiveIntegerField(null=True)
    updated = models.DateField(auto_now=True)
    created = models.DateField(auto_now_add=True)
    slug = models.CharField(max_length=1000,null=True,blank=True)


    def __str__(self):
        return self.name
    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug=slugify(self.name+"-"+str(self.updated))
        return super().save(*args, **kwargs)




class ProductImage(models.Model):
    
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    images = models.ImageField(upload_to='media',null=True)

    def __str__(self):
        return self.product.name
    
class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=100,null=True)
    lastname = models.CharField(max_length=100,null=True)
    email = models.EmailField(max_length=200)
    address_line_1 = models.CharField(max_length=255)
    address_line_2 = models.CharField(max_length=255, blank=True)
    phone_regex = RegexValidator(regex=r'^\d+$', message="Mobile number should only contain digits")
    phone = models.CharField(validators=[phone_regex], max_length=10, null=True)
    city = models.CharField(choices=DIST_CHOICES,max_length=255)
    state = models.CharField(choices=STATE_CHOICES,max_length=255)
    pincode_regex = RegexValidator(regex=r'^\d+$', message="Pincode should only contain digits")
    pincode = models.PositiveIntegerField(null=True,blank=True)

    def __str__(self):
        return self.user.username
    


class Review(models.Model):
    products = models.ManyToManyField(Product)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    feedback = models.TextField(null=True, blank=True)

ecom/templates/cart/checkout.html
{% extends 'home/index.html' %}
{% block banner %}


{% endblock banner %}



{% block contents %}
<div class="container">

<section class="checkout_area padding_top">
    
      <div class="billing_details justify-content-center">
        <div class="row ">
          <div class="col-sm-5 ">
            <form class="row contact_form" action="{% url 'confirmation' %}" method="POST">
              {%csrf_token%}  
            <h4 class="font-weight-bold mt-0 mb-4 ">Select your Delivery Address</h4>

    <!-- Default unchecked -->

                 
                        
                          {% for address in AllAddress %}
                          <div class="container" >
                              <div class="card shadow my-2 col-6 d-flex" style="background-color:#ebc263;">
                                  <div class="card-body"> 
                                      <input type="radio" id="{{ address.id }}" name="selected_addresses" value="{{ address.id }}" checked>
                                      <div class="container">
                                          <p>{{ address.firstname}}</p>
                                          <p>{{ address.address_line_1 }}</p>
                                          {% comment %} <p>{{ address.address_line_2 }}</p>
                                          <p>{{ address.city }} , {{ address.state }}</p>  
                                          <p>{{ address.phone }}</p>
                                          <p>{{ address.pincode }}</p> {% endcomment %}
                                      </div>
                                  </div>
                              </div>
                          </div>
                          {% endfor %}           
                      
             
          </div> 
          
          <div class="col-sm-7 mt-5">
            <div class="order_box" style="background-color:#ebc263;">
              <h2>Your Order</h2>
              <ul class="list">
                <li>
                  <a href="#">Product
                    <span>Total</span>
                  </a>
                </li>
                {% for item in cart_items %}
                <li>
                  <a href=""> {{item.product.name}}
                    <span class="middle">X {{item.quantity}}</span>
                    <span class="last">{{item.product.price}}</span>
                  </a>
                </li>
                {% endfor %}
              </ul>
              <ul class="list list_2">
                <li>
                  <a href="#">Subtotal
                    <span>{{subtotal}}</span>
                  </a>
                </li>
                <li>
                  <a href="#">Shipping
                    <span>Rs. 70.00</span>
                  </a>
                </li>
                <li>
                  <a href="#">Total
                    <span>{{grand_total}}</span>
                  </a>
                </li>
                {% if discount %}
                <li >
                  <a class="font-weight-bold">
                    Coupon Applied.
                  </a>
                </li>
                <li>
                  <a href="#"
                    >Coupon Code : {{coupon.code}}
                  </a>
                </li>
                <li>
                  <a href="#"
                    >Coupon Discount({{coupon.discount}}%)
                    <span> -₹ {{coupon_discount}}</span>
                  </a>
                </li>
                <li>
                  <a href="#"
                    >Payable Amount
                    <span>₹ {{amountToBePaid}}</span>
                  </a>
                </li>
                {% endif %}
                
              </ul>
              <input type="hidden" class="form-control" value="{{subtotal}}" name="total" required/>
              <input type="hidden" class="form-control" value="{{grand_total}}" name="grand_total" required/>
              <input type="hidden" class="form-control" value="{{amountToBePaid}}" name="amountToBePaid" required/>
              <input type="hidden" class="form-control" id="couponCode" value="{{coupon.code }}" name="couponCode" required/>
              <input type="hidden" class="form-control" value="{{coupon_discount}}" name="couponDiscount"required/>
              
              <button class="btn_3 my-3 justify-content-center" style="background-color:black;" type='submit' href="">Proceed to Payment</button>
            </div>
          </div>

        </div>
      </div>
    </div>
  </section>
</form>


<div class="container my-5" >
  <form action="" id="coupon-form" method="POST" required>
  {% csrf_token %}
  <div class="cupon_area">
    <div class="check_title">
      <h2>
        You have discount for purchasing above 1000 ,Use a coupen code 'AAA'
       
      </h2>
    </div>
    <input type="hidden" class="form-control"value="{{grand_total}}" name="grand_total" required/>
    <input  type="text" name="couponCode" placeholder="Enter coupon code" />
    <button class="tp_btn" {% if discount %}disabled{% endif %}>Apply Coupon</button>
   

  </div>
  
</form>
</div> 


  <section class="section-content container mt-5 ">
    

    <article class="" style="background:#ebc263;">
                <br/>
    <h2>&nbsp;&nbsp;Add New Address</h2>
                <div class="card-body">
    
                    <div class="row">
                        <div class="col-md-12">
                            <form class="row contact_form" action="{% url 'addaddress' 1 %}" method="POST">
                                {%csrf_token%}
                                <div class="col-md-6 form-group p_star">
                                    <label>First Name</label>
                                    <input type="text" class="form-control" id="first"  name="firstname" placeholder="First Name"required />
                                </div>
                                <div class="col-md-6 form-group p_star">
                                    <label>Last Name</label>
                                    <input type="text" class="form-control" id="last"  name="lastname" placeholder="Last Name" required/>
                                </div>
                                <div class="col-md-6 form-group p_star">
                                    <label>Phone Number</label>
                                    <input type="text" class="form-control" id="phone"  name="phone"  placeholder="Phone Number"required  pattern="[0-9]+" title="Please enter only digits" maxlength="10"/>
                                </div>
                                <div class="col-md-6 form-group p_star">
                                    <label>Email</label>
                                    <input type="email" class="form-control" id="email"  name="email"placeholder="Email" required/>
                                </div>
                                <div class="col-md-6 form-group p_star">
                                    <label>Address</label>
                                    <input type="text" class="form-control" id="add1"  name="address_line_1" placeholder="Address"required/>
                                </div>
                                <div class="col-md-6 form-group p_star">
                                    <label>Landmark</label>
                                    <input type="text" class="form-control" id="add1"  name="address_line_2" placeholder="Landmark"required/>
                                </div>
                                
                                <div class="col-md-6 form-group p_star">
                                    <label>City</label><br>
                                    <select class="form-select" id="id_city" name="city" required><br>
                                        <option value="">Select city</option>
                                        {% for city in city %}
                                            
                                                <option value="{{ city }}">{{ city }}</option>
                                            
                                        {% endfor %}
                                    </select><br>
                                </div>
                                <div class="col-md-6 form-group p_star">
                                    <label>State</label><br>
                                    <select class="form-select" id="id_state" name="state" required><br>
                                        <option value="">Select State</option>
                                        {% for state in state %}
                
                                                <option value="{{ state }}">{{ state }}</option>
            
                                        {% endfor %}
                                    </select><br>
                                </div>
                                <div class="col-md-6 form-group">
                                    <label>Pin Code</label>
                                    <input type="text" class="form-control" id="pincode" name="pincode"  placeholder="Pincode" required pattern="[0-9]+" title="Please enter only digits" maxlength="6"/>
                                </div>
                                <input type="hidden" class="form-control" name="form_from" value="{{form_from}}" required/>
    
    
                                <br/><br/>
                                <div class="col-sm-12 form-group p_star">
                                    <center>
                                        <button type="submit" name="submit" class=" btn btn-danger " style="height:50px">Save</button>
                                    </center>
                                </div>
                            </form>
                        </div>
    
                        </div>
    
                    </div>
                </div>
            </article>
    
        </main>
        </div>
        </div>
    </section>


</div>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>




{% if msg %}
 <script>
  console.log("here");
  swal("Message for you", "{{msg}}", "info");

</script> 
{% endif %}
{% endblock contents %}

ecom/templates/cart/viewcart.html
{% extends 'home/index.html' %}
{% load static %}
{% block banner %}
<section class="breadcrumb breadcrumb_bg"style="background-image: url('https://wallpapercave.com/wp/wp3646113.jpg'); width:100%;height:60%;">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="breadcrumb_iner">
            <div class="breadcrumb_iner_item">
              <h2 class="" style="color:red">Cart Products</h2>
              <p class=" text-white"><strong>Home <span>-</span>Cart Products</stron</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>{% endblock banner %}

{% block contents %}



      <div class="container-fluid">
        <br><br><br>
{%if not cart_items%}
        <h2 class="text-center text-danger">Your Cart is Empty</h2>
        <div class="text-center">
            <a href="{%url 'userproduct' 0 %}">Continue shopping..</a>
        </div>
        {%else%}
        <section class="cart_area padding_top w-100">
            <form class="row contact_form" action="{% url 'checkout' %}" method="POST" >
             
                  {% csrf_token %}
                  <div class="container">
                    <div class="cart_inner">
                      <div class="table-responsive">
                        <table class="table">
                          <thead>
                            <tr>
                              <th scope="col">Product</th>
                              <th scope="col">Price</th>
                              <th scope="col">Quantity</th>
                              <th scope="col">Total</th>
                            </tr>
                          </thead>
                          <tbody>
              
                            {% for item in cart_items %}
                            <tr>
                              <td>
                                <div class="media">
                                  <div class="d-flex">
                                    <a href="{% url 'singleproduct' item.product.id %}"><img src="{{ item.product.productimage_set.first.images.url }}" alt="" style="height: 70px;"></a>
                                  </div>
                                  <div class="media-body">
                                    <p>{{ item.product.name }}</p>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <h5>	
                                  ₹ {{ item.product.price }}</h5>
                              </td>
                              {% if item.product.stock == 0 %}
                              <td>
                                <div class="product_count">
                                <i class="text-danger">Product out of stock</i>
                                </div>
                                <td>
                                  <h5><del>{{ item.price }} </del></h5>
                                </td>
                              </td>
                              {% else %}
                              {% comment %} <td>
                                <div class="product_count" >

                                   <a href="{% url 'removecartitem' item.product.id %}"  > <i class="fas fa-minus"></i></a>
                                  <input class="input-number" name="quantity" type="text" value="{{item.quantity}}" min="0" max="100">
                                  <a href="{% url 'addcartitem' item.product.id %}" > <i class="fas fa-plus"></i></a>
                                </div>                      
                              </td> {% endcomment %}



                              <td>
                                <div class="product_count">
                                  <a href="{% url 'removecartitem' item.product.id %}" class="decrement-quantity" data-product-id="{{item.product.id}}"><i class="fas fa-minus"></i></a>
                                  <input class="input-number" name="quantity" type="text" value="{{item.quantity}}" min="0" max="100">
                                  <a href="{% url 'addcartitem' item.product.id %}" class="increment-quantity" data-product-id="{{item.product.id}}"><i class="fas fa-plus"></i></a>
                                </div> 
                              </td>
                              
                              
                              

                              <td>
                                <h5>{{ item.price }}</h5>
                              </td>
                              {% endif %}
                              <td>
                                <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                  <a href="{% url 'removecartproduct' item.product.id  %}" onclick="return confirm('Are You Sure?')" class="text-danger"><i class="fas fa-trash fa-lg"></i></a>
                                </div>
                              </td>
                            </tr>
                            {% endfor %}
                            <tr class="bottom_button">
                              <td></td>
                              <td></td>
                              <td></td>
                              <td></td>
                            </tr>
                            <tr>
                              <td>
                              </td>

                              <td></td>
                              <td>
                                <h5>Subtotal</h5>
                              </td>
                              <td>
                                <h5>₹{{total}}</h5>
                              </td>
                            </tr>

                          </tbody>
                        </table>

                    <br>
                        <div class="checkout_btn_inner float-right">
                          <a class="btn_1" href="{% url 'userproduct' 0 %}" style="background-color:grey;" onmouseover="this.style.backgroundColor='red';"onmouseout="this.style.backgroundColor='grey';">Continue Shopping</a>
                          {% if total > 0 %}
                          <button type ="submit" class="btn_1 checkout_btn_1" style="background-color:grey; border: 2px solid grey;" onmouseover="this.style.backgroundColor='green';" onmouseout="this.style.backgroundColor='grey';">

                            Proceed to checkout
                          </button>
                          {% endif %}
                        
                        </div>
                      </div>
                      
                    </div>
             </form>
        </section>
      </div>
{% endif %}

  <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
  <script>
    function confirmDelete(event) {
        event.preventDefault(); // prevent the link from redirecting immediately
        alertify.confirm('Message', 'Are You Sure Want to Delete This', function(){
            window.location.href = event.target.href; // redirect to the delete URL
        }, function(){ 
            alertify.error('Cancel')
        });
   }
</script> 
<script>
  $(document).ready(function() {
    $('.product_count').on('click', '.decrement-quantity, .increment-quantity', function(event) {
      event.preventDefault();
  
      var $link = $(this);
      var productId = $link.data('product-id');
      var quantityInput = $link.siblings('.input-number');
      var quantity = parseInt(quantityInput.val());
      var newQuantity = quantity;
  
      if ($link.hasClass('decrement-quantity') && quantity > 0) {
        newQuantity = quantity - 1;
      } else if ($link.hasClass('increment-quantity') && quantity < 100) {
        newQuantity = quantity + 1;
      }
  
      $.ajax({
        url: '/cart/update/',
        method: 'POST',
        data: {
          'product_id': productId,
          'quantity': newQuantity,
          'csrfmiddlewaretoken': '{{ csrf_token }}'
        },
        success: function(data) {
          if (data.success) {
            quantityInput.val(newQuantity);
          }
        }
      });
    });
  });
  </script>

{% endblock contents %}

ecom/templates/cart/wishlist.html
{% extends 'home/index.html' %}

{% block banner %}
<section class="breadcrumb breadcrumb_bg"style="background-image: url('https://cdn.shopify.com/s/files/1/0536/3594/0515/articles/blog-banner.jpg?v=1654067107'); width:100%;height:60%;">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="breadcrumb_iner">
            <div class="breadcrumb_iner_item">
              <h2 class="" style="color:red">WishList</h2>
              <p class="text-white ">Home <span>-</span>Your Wishlist Products</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock banner %}
{% load static %}


{% block contents %}

<section class="cart_area padding_top" >
    <center>
       
    </center>
    <div class="container">
        {%if not witems%}
            <h2 class="text-center text-danger">Your wish list is empty</h2>
            <div class="text-center">
                <a href="{%url 'userproduct' 0 %}">Continue shopping..</a>
            </div>
        {%else%}

        <div class="cart_inner">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr style="height:2px;">
                    <th scope="col">Product</th>
                    <th scope="col">Price</th>
                    <th></th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for item in witems%}
                    <tr>
                    <td>
                    <div class="media">
                        <div class="d-flex">
                            <img style="height:100px;width:90px"  src="{{item.product.productimage_set.first.images.url}}" alt="">
                        </div>
                        <div class="media-body">
                            <p>{{item.product.name}}</p>
                        </div>
                    </div>
                </td>
                <td>
                    <h5>${{item.product.price}}</h5>
                </td>
                <td class="text-right">
                    {% if item.product.stock > 0 %}
                        <a href="{% url 'add_to_cart' item.product.id %}"><i class="fas fa-cart-plus"></i></a>
                    {%else%}
                        <a> Currently, Out of Stock </a>
                    {%endif%}

                </td>
                <td class="text-right">
                    <a href="{% url 'remove_from_wishlist' item.product.id %}" onclick="return confirm('Are You sure?')"><i class="fas fa-trash"></i></a>

                </td>
            </div>

            </tr>
                {% endfor %}
                </tbody>
                </table>
        </div>
        {%endif%}
    </div>
</section>

<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>

    {% comment %} <script>
        alertify.set('notifier','position', 'top-right');
        {% for msg in messages %}
            alertify.success('{{ msg }}');
        {% endfor %}
        
    </script> {% endcomment %}

    <script>
        function confirmDelete(event) {
            event.preventDefault(); // prevent the link from redirecting immediately
            alertify.confirm('Message', 'Are You Sure Want to Delete This', function(){
                window.location.href = event.target.href; // redirect to the delete URL
            }, function(){ 
                alertify.error('Cancel')
            });
       }
</script>

{% endblock contents %}